---

- name: Add Client Domain Name and IP address to Server Hosts File
  lineinfile:
    backup: yes
    dest: /etc/hosts
    line: "{{syslogng_server_ip }}      {{ syslogng_server_prefix }}.{{ syslogng_server_suffix }}"

