---
# tasks file for ansible-role-syslogng-client

- include: hosts.yml
  become: true
  tags: hosts

- include: syslogng.yml
  become: true
  tags: agent

- include: ssl-selfsign.yml
  become: true
  tags: ssl
