#syslogng-client###client-variables
syslogng_client_ip: [ hostname -i on syslogng-client ]
syslogng_dn_prefix: [ hostname -s on syslogng-client ]
syslogng_dn_suffix: [ hostname -d on syslogng-client ]

#syslogng-client###server-variables
syslogng_server_ip: [ hostname -i on syslogng-server ]
syslogng_server_prefix: [ hostname -i on syslogng-server ]
syslogng_server_suffix: [ hostname -i on syslogng-server ]
syslogng_server_protocol: tls
syslogng_server_port: 514
#syslogng_server_cert: |
#  -----BEGIN CERTIFICATE-----
#  paste syslogng-server/relay cert in here with 2 space indent
#  -----END CERTIFICATE-----
