---
- name: Ensure /opt/oulib/users/bin exists
  file:
    path: /opt/oulib/users/bin
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: Copy motd
  copy:
    src: motd.sh
    dest: /etc/profile.d/
    mode: 0644
    owner: root
    group: root

- name: Copy helper scripts
  copy:
    src: "{{ item }}"
    dest: /opt/oulib/users/bin/
    mode: 0744
    owner: root
    group: root
  with_items:
    - printusers.sh
    - printsecurepath.sh

- name: Copy sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0400
    owner: root
    group: root
    validate: 'visudo -cf %s'
