---

# Provision user accounts and ssh keys
- include: users.yml
  become: true
  tags:
  - users_users

# Configure sshd and ssh defaults
- include: ssh.yml
  become: true
  tags:
  - users_ssh

# Configure Vagrant specific settings
- include: virtualbox.yml
  when: (ansible_virtualization_type == "virtualbox") 
          and (ansible_virtualization_role == "guest")
  become: true
  tags:
  - users_virtualbox

# Install support scripts and other files    
- include: assets.yml
  become: true
  tags:
  - users_assets

# Restart ssh service
- include: services.yml
  become: true
  tags:
  - users_services
