---

# configure sshd and ssh 
- name: Copy sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
- name: Copy ssh_config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    mode: 0644
    owner: root
    group: root

# Squash possible GitHub connection errors 
- name: Ensure /etc/ssh/ssh_known_hosts exists
  file:
    path: /etc/ssh/ssh_known_hosts
    state: touch
    mode: 0644
    owner: root
    group: root
- name: Get github ssh fingerprints.
  command: ssh-keyscan github.com
  register: github_ssh_key
  check_mode: no
- name: tell the host about our servers it might want to ssh to
  known_hosts:
    path: '/etc/ssh/ssh_known_hosts'
    host: 'github.com'
    key: "{{ github_ssh_key.stdout }}"
    state: present
